name: Arm64 Compile
run-name: ${{ github.actor }} Compiling ARM64
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        BUILD_TARGET: [Release]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v5
        with:
          path: /artifacts/         
      - name: Build prerequisites
        env:
          EW_HOME: /opt/earthworm
          EW_VERSION: earthworm-v8.0b9
          EW_INSTALLATION: INST_UTAH
          EW_INSTALL_BITS: 64
          EW_BITS: 64
          EW_CPPCFLAGS: "-D_LINUX -Dlinux -D_INTEL -D_USE_SCHED -D_USE_PTHREADS -D_USE_TERMIOS -D_FILE_OFFSET_BITS=64 -I/opt/earthworm/earthworm-v8.0b9/include -I/usr/include -I/usr/include/tirpc" 
          PLATFORM: LINUX
        run: |
          sudo apt-get update
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y tar
          sudo apt-get install -y wget
          sudo apt-get install -y file
          sudo apt-get install -y clang
          sudo apt-get install -y make
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja-build 
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libtirpc-dev
          sudo apt-get install -y sed
          sudo mkdir -p /artifacts/
          sudo mkdir -p /opt/earthworm
          sudo mkdir -p /usr/local/lib
          sudo mkdir -p /usr/local/include
          wget -q https://github.com/EarthScope/libmseed/archive/refs/tags/v3.2.4.tar.gz
          tar -xf v3.2.4.tar.gz
          rm v3.2.4.tar.gz
          cd libmseed-3.2.4
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build build
          sudo cmake --install build
          cd ..
          rm -rf libmseed-3.2.4
          wget -q https://github.com/EarthScope/libslink/archive/refs/tags/v4.2.0.tar.gz
          tar -xf v4.2.0.tar.gz
          rm v4.2.0.tar.gz
          cd libslink-4.2.0
          make static
          sudo make install
          cd ../
          rm -rf libslink-4.2.0
          wget -q https://github.com/gabime/spdlog/archive/refs/tags/v1.17.0.tar.gz
          tar -xf v1.17.0.tar.gz
          cd spdlog-1.17.0
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DSPDLOG_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/
          cmake --build build
          sudo cmake --install build
          cd ../
          rm -rf spdlog-1.17.0
          wget https://gitlab.com/seismic-software/earthworm/-/archive/v8.0b9/earthworm-v8.0b9.tar.gz
          tar -xf earthworm-v8.0b9.tar.gz
          rm earthworm-v8.0b9.tar.gz
          sudo mv earthworm-v8.0b9 /opt/earthworm/
          cd /opt/earthworm/earthworm-v8.0b9/src
          export CC=gcc
          export CXX=g++
          export FC=gfortran
          export PATH="${EW_HOME}/${EW_VERSION}/bin:${PATH}"
          export WARNFLAGS="-Wall -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unknown-pragmas -Wno-pragmas -Wformat -Wdeclaration-after-statement"
          export CFLAGS="-g -pthread -fPIC ${WARNFLAGS}"
          export CXXFLAGS="${CFLAGS}"
          export FFLAGS="-O -g -Wuninitialized -Werror=line-truncation -ffpe-trap=invalid,zero,overflow -fbacktrace"
          export CPPFLAGS="-D_LINUX -Dlinux -D_INTEL -D_USE_SCHED -D_USE_PTHREADS -D_USE_TERMIOS -D_FILE_OFFSET_BITS=64 -I${EW_HOME}/${EW_VERSION}/include -I/usr/include -I/usr/include/tirpc"
          export LDADD="-ltirpc"
          export GLOBALFLAGS="${CFLAGS} ${CPPFLAGS}"
          make unix
          cd
          wget https://github.com/open-telemetry/opentelemetry-cpp/archive/refs/tags/v1.25.0.tar.gz
          tar -xf v1.25.0.tar.gz
          rm v1.25.0.tar.gz
          cd opentelemetry-cpp-1.25.0
          cmake -B build -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_PROMETHEUS=OFF -DWITH_BENCHMARK=OFF -DCMAKE_CXX_COMPILER=clang++ -DWITH_EXAMPLES=OFF -DWITH_ABI_VERSION_1=OFF -DWITH_ABI_VERSION_2=ON -DWITH_OTLP_HTTP=ON
          cmake --build build -j 4
          sudo cmake --install build
          cd ../
          rm -rf opentelemetry-cpp-1.25.0
      - name: Build project        
        run: |
          mkdir -p /artifacts
          pwd
          ls
          ls /usr/local/lib
          ls /opt/earthworm
          cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic" -DBUILE_EW=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build
