name: Arm64 Compile
run-name: ${{ github.actor }} Compiling ARM64
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        BUILD_TARGET: [Release]
    steps:
      - name: Build prerequisites
        env:
          EW_HOME: /opt/earthworm
          EW_VERSION: earthworm-v8.0b9
          EW_INSTALLATION: INST_UTAH
          EW_INSTALL_BITS: 64
          EW_BITS: 64
          EW_CPPCFLAGS: "-D_LINUX -Dlinux -D_INTEL -D_USE_SCHED -D_USE_PTHREADS -D_USE_TERMIOS -D_FILE_OFFSET_BITS=64 -I/opt/earthworm/earthworm-v8.0b9/include -I/usr/include -I/usr/include/tirpc" 
          PLATFORM: LINUX
        run: |
          sudo apt-get update
          sudo apt-get install -y g++
          sudo apt-get install -y gfortran
          sudo apt-get install -y tar
          sudo apt-get install -y wget
          sudo apt-get install -y file
          sudo apt-get install -y clang
          sudo apt-get install -y make
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja-build 
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libtirpc-dev
          sudo apt-get install -y sed
          sudo mkdir -p /opt/earthworm
          sudo mkdir -p /usr/local/lib
          sudo mkdir -p /usr/local/include
          wget -q https://github.com/EarthScope/libmseed/archive/refs/tags/v3.2.4.tar.gz
          tar -xf v3.2.4.tar.gz
          rm v3.2.4.tar.gz
          cd libmseed-3.2.4
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build build
          sudo cmake --install build
          cd ..
          rm -rf libmseed-3.2.4
          wget -q https://github.com/EarthScope/libslink/archive/refs/tags/v4.2.0.tar.gz
          tar -xf v4.2.0.tar.gz
          rm v4.2.0.tar.gz
          cd libslink-4.2.0
          make static
          make install
          sudo mv libslink.a /usr/local/lib/
          cd ../
          rm -rf libslink-4.2.0
          wget -q https://github.com/gabime/spdlog/archive/refs/tags/v1.17.0.tar.gz
          tar -xf v1.17.0.tar.gz
          cd spdlog-1.17.0
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DSPDLOG_BUILD_SHARED=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/
          cmake --build build
          sudo cmake --install build
          cd ../
          rm -rf spdlog-1.17.0
      - name:
        run: ls
